version: '3.8'

services:
  vehicle_inference:
    build:
      context: .
      dockerfile: ./docker/vehicle_inference/Dockerfile
    image: vehicle-inference-node:latest
    container_name: vehicle-inference-node
    command: ros2 launch vehicle_inference vehicle_inference.launch.py
    volumes:
      - ./models:/models
    networks:
      - tfm_ros_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

#  ROS2 data collector container
#  data_collector:
#    build:
#      context: .
#      dockerfile: ./docker/data_collector/Dockerfile
#    image: data-collector-node:latest
#    container_name: data-collector-node
#    command: /bin/sh -c "sleep 15 && ros2 launch data_collector data_collector.launch.py"
#    volumes:
#      - ./data:/data
#    networks:
#      - tfm_ros_net

networks:
  tfm_ros_net:
