version: '3.8'

services:
  build_image:
    build:
      context: .
      dockerfile: ./docker/cpu/Dockerfile
    image: tfm-autonomous-drive-system:latest
    command: echo "Image built"

  vehicle_inference:
    build:
      context: .
      dockerfile: ./docker/cuda/Dockerfile
    image: tfm-autonomous-drive-inference:latest
    container_name: vehicle-inference-node
    command: ros2 launch vehicle_inference vehicle_inference.launch.py
    volumes:
      - ./models:/models
    networks:
      - shared_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  vehicle_control:
    image: tfm-autonomous-drive-system:latest
    container_name: vehicle-control-node
    command: ros2 launch vehicle_control vehicle_control.launch.py
    networks:
      - shared_network

#  # ROS2 data collector container
#  data_collector:
#    image: tfm-autonomous-drive-system:latest
#    container_name: data-collector-node
#    command: bash /recording-rosbag.sh
#    volumes:
#      - ./data:/data
#    networks:
#      - shared_network

networks:
  shared_network:
    external:
      name: tfm_ros_net
